# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_auto_20190329_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_name',
            name='ave_rate',
            field=models.IntegerField(default='5'),
        ),
    ]
