# Generated by Django 2.2 on 2019-04-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20190426_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_name',
            name='rate',
            field=models.ManyToManyField(through='Login.Rate', to='Login.User'),
        ),
    ]
