# Generated by Django 2.2 on 2019-04-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_auto_20190426_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likeCount',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likeUser',
        ),
    ]
