# Generated by Django 2.2 on 2019-05-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0011_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='image',
        ),
    ]
