# Generated by Django 2.2 on 2019-05-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0013_restaurant_name_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_name',
            name='img',
            field=models.ImageField(default='', height_field=300, upload_to='img', width_field=100),
        ),
    ]
