# Generated by Django 2.2 on 2019-05-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0014_auto_20190530_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_name',
            name='img',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
